[k3s_master]
k3s-master ansible_host=192.168.56.33 k3s_node_ip=192.168.56.33

[k3s_workers]
k3s-worker-1 ansible_host=192.168.56.34 k3s_node_ip=192.168.56.34
k3s-worker-2 ansible_host=192.168.56.35 k3s_node_ip=192.168.56.35

[k3s_cluster:children]
k3s_master
k3s_workers

[k3s_cluster:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_become=true
ansible_become_method=sudo
ansible_become_password=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
